@baseurl = http://localhost:5001/api

### Register
POST {{baseurl}}/auth/register
Content-Type: application/json

{
    "name" : "test",
    "email": "test@gmail.com",
    "password": "password"
} 

###Login
POST {{baseurl}}/auth/login
Content-Type: application/json

{
    "email" : "test@gmail.com",
    "password": "password"
}